###############################################################################
#
# (c) Copyright IBM Corp. 2017
#
#  This program and the accompanying materials are made available
#  under the terms of the Eclipse Public License v1.0 and
#  Apache License v2.0 which accompanies this distribution.
#
#      The Eclipse Public License is available at
#      http://www.eclipse.org/legal/epl-v10.html
#
#      The Apache License v2.0 is available at
#      http://www.opensource.org/licenses/apache2.0.php
#
# Contributors:
#    Multiple authors (IBM Corp.) - initial implementation and documentation
###############################################################################

platform: x64
configuration: Debug
shallow_clone: true
clone_depth: 1

environment:
  GTEST_FILTER: '-*dump_test_create_dump_*:*NumaSetAffinity:*NumaSetAffinitySuspended:PortSysinfoTest.sysinfo_test0'
  GTEST_COLOR: '1'
  TEST_RESULT_DIR: '%APPVEYOR_BUILD_FOLDER%\test_results'
  GTEST_OUTPUT: 'xml:%TEST_RESULT_DIR%\'

before_build:
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - cmd: cmake -Wdev -G "Visual Studio 14 2015 Win64" -Ccmake\caches\Appveyor.cmake.

build:
  project: omr.sln
  parallel: true

test_script:
  - cmd: mkdir %TEST_RESULT_DIR%
  - cmd: ctest -V -C Debug
  - ps: scripts\Appveyor-ProcessTests.ps1
